version: 0.2

phases:
  install:
    commands:
      - echo "Lancement de la phase d'installation"
      - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
  pre_build:
    commands:
      - echo "Lancement de la phase de pre-build"	
      - echo "Récupération des variables dans secrets manager"
      - export DB_HOST=$(aws secretsmanager get-secret-value --secret-id Secret_Mysql_lenny --query SecretString --output text | jq -r .DB_HOST)
      - export DB_PORT=$(aws secretsmanager get-secret-value --secret-id Secret_Mysql_lenny --query SecretString --output text | jq -r .DB_PORT)
      - export DB_DATABASE=$(aws secretsmanager get-secret-value --secret-id Secret_Mysql_lenny --query SecretString --output text | jq -r .DB_DATABASE)
      - export DB_USERNAME=$(aws secretsmanager get-secret-value --secret-id Secret_Mysql_lenny --query SecretString --output text | jq -r .DB_USERNAME)
      - export DB_PASSWORD=$(aws secretsmanager get-secret-value --secret-id Secret_Mysql_lenny --query SecretString --output text | jq -r .DB_PASSWORD)
      - composer install --no-interaction --prefer-dist --optimize-autoloader
  build:
    commands:
      - echo "Lancement de la phase de build"
      - php artisan cache:clear 
      - echo "Running migrations"
      - php artisan migrate --force
      - rm -f public/storage && php artisan storage:link
  post_build:
    commands:
      - echo "Lance de la phase de post-build"
      - zip -r deploy.zip .
artifacts:
  files:
    - deploy.zip
  discard-paths: yes
