version: 0.2

phases:
  install:
    commands:
      - echo "Starting the install phase"
      - apt-get update && apt-get install -y software-properties-common
      - add-apt-repository ppa:ondrej/php
      - apt-get update && apt-get install -y \
          curl \
          php8.2-cli \
          php8.2-mbstring \
          php8.2-xml \
          php8.2-zip \
          php8.2-curl \
          php8.2-mysql \
          php8.2-gd \
          unzip \
          git
      - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

  pre_build:
    commands:
      - echo "Starting the pre-build phase"
      - docker --version  # Vérifie la version de Docker
      - composer install --no-interaction --prefer-dist --optimize-autoloader

  build:
    commands:
      - echo "Starting the build phase"
      - php artisan config:cache
      - php artisan route:cache

  post_build:
    commands:
      - echo "Starting the post-build phase"
      - zip -r deploy.zip .
      - echo "Creating new application version in Elastic Beanstalk"
      - aws elasticbeanstalk create-application-version --application-name Applications-Lenny --version-label build-v1 --source-bundle S3Bucket=$CODEBUILD_S3_BUCKET,S3Key=$CODEBUILD_BUILD_ID/deploy.zip
      - aws elasticbeanstalk update-environment --environment-name Applications-Lenny-env --version-label build-v1

artifacts:
  files:
    - deploy.zip
  discard-paths: yes
